# Generated by Django 4.0.4 on 2022-07-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Aadharnumber',
            new_name='Aadhar',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Mobilenumber',
            new_name='Contact',
        ),
    ]
