# Generated by Django 4.0.4 on 2022-08-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_users_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='aadhar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='contact',
            field=models.CharField(max_length=50),
        ),
    ]
