# Generated by Django 4.0.4 on 2022-08-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_users_aadhar_alter_users_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='aadhar',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
